// swiftlint:disable all
// Generated using SwiftGen — https://github.com/SwiftGen/SwiftGen

#if os(OSX)
  import AppKit.NSImage
  internal typealias AssetColorTypeAlias = NSColor
  internal typealias AssetImageTypeAlias = NSImage
#elseif os(iOS) || os(tvOS) || os(watchOS)
  import UIKit.UIImage
  internal typealias AssetColorTypeAlias = UIColor
  internal typealias AssetImageTypeAlias = UIImage
#endif

// swiftlint:disable superfluous_disable_command
// swiftlint:disable file_length

// MARK: - Asset Catalogs

// swiftlint:disable identifier_name line_length nesting type_body_length type_name
internal enum Asset {
  internal enum Coins {
    internal static let ada = ImageAsset(name: "ADA")
    internal static let ae = ImageAsset(name: "AE")
    internal static let aion = ImageAsset(name: "AION")
    internal static let aoa = ImageAsset(name: "AOA")
    internal static let ardr = ImageAsset(name: "ARDR")
    internal static let ark = ImageAsset(name: "ARK")
    internal static let bat = ImageAsset(name: "BAT")
    internal static let bcd = ImageAsset(name: "BCD")
    internal static let bch = ImageAsset(name: "BCH")
    internal static let bcn = ImageAsset(name: "BCN")
    internal static let bnb = ImageAsset(name: "BNB")
    internal static let bnt = ImageAsset(name: "BNT")
    internal static let btc = ImageAsset(name: "BTC")
    internal static let btcp = ImageAsset(name: "BTCP")
    internal static let btg = ImageAsset(name: "BTG")
    internal static let btm = ImageAsset(name: "BTM")
    internal static let bts = ImageAsset(name: "BTS")
    internal static let cmt = ImageAsset(name: "CMT")
    internal static let cnx = ImageAsset(name: "CNX")
    internal static let crpt = ImageAsset(name: "CRPT")
    internal static let dash = ImageAsset(name: "DASH")
    internal static let dcn = ImageAsset(name: "DCN")
    internal static let dcr = ImageAsset(name: "DCR")
    internal static let dgb = ImageAsset(name: "DGB")
    internal static let dgd = ImageAsset(name: "DGD")
    internal static let doge = ImageAsset(name: "DOGE")
    internal static let ela = ImageAsset(name: "ELA")
    internal static let elf = ImageAsset(name: "ELF")
    internal static let emc = ImageAsset(name: "EMC")
    internal static let eos = ImageAsset(name: "EOS")
    internal static let etc = ImageAsset(name: "ETC")
    internal static let eth = ImageAsset(name: "ETH")
    internal static let etp = ImageAsset(name: "ETP")
    internal static let fun = ImageAsset(name: "FUN")
    internal static let gas = ImageAsset(name: "GAS")
    internal static let gbyte = ImageAsset(name: "GBYTE")
    internal static let gnt = ImageAsset(name: "GNT")
    internal static let gxs = ImageAsset(name: "GXS")
    internal static let hc = ImageAsset(name: "HC")
    internal static let hot = ImageAsset(name: "HOT")
    internal static let ht = ImageAsset(name: "HT")
    internal static let icx = ImageAsset(name: "ICX")
    internal static let iost = ImageAsset(name: "IOST")
    internal static let kcs = ImageAsset(name: "KCS")
    internal static let kin = ImageAsset(name: "KIN")
    internal static let kmd = ImageAsset(name: "KMD")
    internal static let knc = ImageAsset(name: "KNC")
    internal static let link = ImageAsset(name: "LINK")
    internal static let lrc = ImageAsset(name: "LRC")
    internal static let lsk = ImageAsset(name: "LSK")
    internal static let ltc = ImageAsset(name: "LTC")
    internal static let maid = ImageAsset(name: "MAID")
    internal static let mana = ImageAsset(name: "MANA")
    internal static let mco = ImageAsset(name: "MCO")
    internal static let miota = ImageAsset(name: "MIOTA")
    internal static let mith = ImageAsset(name: "MITH")
    internal static let mkr = ImageAsset(name: "MKR")
    internal static let moac = ImageAsset(name: "MOAC")
    internal static let mona = ImageAsset(name: "MONA")
    internal static let nano = ImageAsset(name: "NANO")
    internal static let nas = ImageAsset(name: "NAS")
    internal static let neo = ImageAsset(name: "NEO")
    internal static let npxs = ImageAsset(name: "NPXS")
    internal static let nxt = ImageAsset(name: "NXT")
    internal static let omg = ImageAsset(name: "OMG")
    internal static let ont = ImageAsset(name: "ONT")
    internal static let oxy = ImageAsset(name: "OXY")
    internal static let pivx = ImageAsset(name: "PIVX")
    internal static let powr = ImageAsset(name: "POWR")
    internal static let ppt = ImageAsset(name: "PPT")
    internal static let qash = ImageAsset(name: "QASH")
    internal static let qtum = ImageAsset(name: "QTUM")
    internal static let rdd = ImageAsset(name: "RDD")
    internal static let rep = ImageAsset(name: "REP")
    internal static let rhoc = ImageAsset(name: "RHOC")
    internal static let sc = ImageAsset(name: "SC")
    internal static let snt = ImageAsset(name: "SNT")
    internal static let steem = ImageAsset(name: "STEEM")
    internal static let strat = ImageAsset(name: "STRAT")
    internal static let sub = ImageAsset(name: "SUB")
    internal static let theta = ImageAsset(name: "THETA")
    internal static let trx = ImageAsset(name: "TRX")
    internal static let ttu = ImageAsset(name: "TTU")
    internal static let tusd = ImageAsset(name: "TUSD")
    internal static let usdc = ImageAsset(name: "USDC")
    internal static let usdt = ImageAsset(name: "USDT")
    internal static let vet = ImageAsset(name: "VET")
    internal static let wan = ImageAsset(name: "WAN")
    internal static let waves = ImageAsset(name: "WAVES")
    internal static let wax = ImageAsset(name: "WAX")
    internal static let wtc = ImageAsset(name: "WTC")
    internal static let xem = ImageAsset(name: "XEM")
    internal static let xin = ImageAsset(name: "XIN")
    internal static let xlm = ImageAsset(name: "XLM")
    internal static let xmr = ImageAsset(name: "XMR")
    internal static let xrp = ImageAsset(name: "XRP")
    internal static let xtz = ImageAsset(name: "XTZ")
    internal static let xvg = ImageAsset(name: "XVG")
    internal static let xzc = ImageAsset(name: "XZC")
    internal static let zec = ImageAsset(name: "ZEC")
    internal static let zen = ImageAsset(name: "ZEN")
    internal static let zil = ImageAsset(name: "ZIL")
  }
  internal enum Colors {
    internal static let black = ColorAsset(name: "black")
    internal static let blueterium10 = ColorAsset(name: "blueterium10")
    internal static let blueterium100 = ColorAsset(name: "blueterium100")
    internal static let blueterium30 = ColorAsset(name: "blueterium30")
    internal static let blueterium80 = ColorAsset(name: "blueterium80")
    internal static let darkterium10 = ColorAsset(name: "darkterium10")
    internal static let darkterium100 = ColorAsset(name: "darkterium100")
    internal static let darkterium30 = ColorAsset(name: "darkterium30")
    internal static let darkterium50 = ColorAsset(name: "darkterium50")
    internal static let darkterium60 = ColorAsset(name: "darkterium60")
    internal static let darkterium80 = ColorAsset(name: "darkterium80")
    internal static let green = ColorAsset(name: "green")
    internal static let oceanBlue = ColorAsset(name: "oceanBlue")
    internal static let orange = ColorAsset(name: "orange")
    internal static let red = ColorAsset(name: "red")
    internal static let white = ColorAsset(name: "white")
    internal static let yeterium = ColorAsset(name: "yeterium")
  }
  internal enum FImages {
    internal static let dashboardBuyCryptoIcon = ImageAsset(name: "DashboardBuyCryptoIcon")
    internal static let dashboardCashOutIcon = ImageAsset(name: "DashboardCashOutIcon")
    internal static let dashboardExchangeIcon = ImageAsset(name: "DashboardExchangeIcon")
    internal static let dashboardHistoryIcon = ImageAsset(name: "DashboardHistoryIcon")
    internal static let dashboardProfileIcon = ImageAsset(name: "DashboardProfileIcon")
    internal static let dashboardSendIcon = ImageAsset(name: "DashboardSendIcon")
    internal static let dashboardTopUpIcon = ImageAsset(name: "DashboardTopUpIcon")
  }
  internal enum Images {
    internal static let aboutCrypteriumLogo = ImageAsset(name: "aboutCrypteriumLogo")
    internal static let aboutFb = ImageAsset(name: "aboutFb")
    internal static let aboutT = ImageAsset(name: "aboutT")
    internal static let aboutTw = ImageAsset(name: "aboutTw")
    internal static let authCrptLogo = ImageAsset(name: "AuthCrptLogo")
    internal static let authCrptLogoV2 = ImageAsset(name: "AuthCrptLogoV2")
    internal static let confirmSmsLogo = ImageAsset(name: "ConfirmSmsLogo")
    internal static let authLogoSmall = ImageAsset(name: "authLogoSmall")
    internal static let authLogoWhite = ImageAsset(name: "authLogoWhite")
    internal static let backgroundBtnKB = ImageAsset(name: "backgroundBtnKB")
    internal static let backgroundBtnKBV2 = ImageAsset(name: "backgroundBtnKBV2")
    internal static let bulletOff = ImageAsset(name: "bulletOff")
    internal static let bulletOn = ImageAsset(name: "bulletOn")
    internal static let bulletWrong = ImageAsset(name: "bulletWrong")
    internal static let checkbox = ImageAsset(name: "checkbox")
    internal static let checkboxOff = ImageAsset(name: "checkboxOff")
    internal static let checkboxOn = ImageAsset(name: "checkboxOn")
    internal static let checkboxSelected = ImageAsset(name: "checkboxSelected")
    internal static let eye = ImageAsset(name: "eye")
    internal static let faceID = ImageAsset(name: "faceID")
    internal static let finalLogo = ImageAsset(name: "finalLogo")
    internal static let iconEyeEyeClose = ImageAsset(name: "iconEyeEyeClose")
    internal static let progressDot = ImageAsset(name: "progressDot")
    internal static let removeKB = ImageAsset(name: "removeKB")
    internal static let touchID = ImageAsset(name: "touchID")
    internal static let cardBlockedIcon = ImageAsset(name: "CardBlockedIcon")
    internal static let cardContextMenu = ImageAsset(name: "CardContextMenu")
    internal static let cardHistoryEmptyImage = ImageAsset(name: "CardHistoryEmptyImage")
    internal static let cardMainImage = ImageAsset(name: "CardMainImage")
    internal static let cardPayIcon = ImageAsset(name: "CardPayIcon")
    internal static let cardPayloadIcon = ImageAsset(name: "CardPayloadIcon")
    internal static let cardActivationImage = ImageAsset(name: "CardActivationImage")
    internal static let cardApplyIdentity = ImageAsset(name: "CardApplyIdentity")
    internal static let cardApplyPhotoInstructionSignature = ImageAsset(name: "CardApplyPhotoInstructionSignature")
    internal static let cardApplyResidence = ImageAsset(name: "CardApplyResidence")
    internal static let cardApplySignature = ImageAsset(name: "CardApplySignature")
    internal static let cardOrderSuccess = ImageAsset(name: "CardOrderSuccess")
    internal static let cardPaymentPin = ImageAsset(name: "CardPaymentPin")
    internal static let cardOrderDeliveryExpress = ImageAsset(name: "CardOrderDeliveryExpress")
    internal static let cardOrderDeliveryRegular = ImageAsset(name: "CardOrderDeliveryRegular")
    internal static let cardApplyTariffsAdvantage = ImageAsset(name: "CardApplyTariffsAdvantage")
    internal static let cardApplyTariffsCard = ImageAsset(name: "CardApplyTariffsCard")
    internal static let cardApplyTariffsDisadventage = ImageAsset(name: "CardApplyTariffsDisadventage")
    internal static let cardApplyTariffsInfo = ImageAsset(name: "CardApplyTariffsInfo")
    internal static let cardPayloadCardIcon = ImageAsset(name: "CardPayloadCardIcon")
    internal static let cardPayloadCrossDown = ImageAsset(name: "CardPayloadCrossDown")
    internal static let cardPayloadTimeIcon = ImageAsset(name: "CardPayloadTimeIcon")
    internal static let cardPreorderAdventagesChoose = ImageAsset(name: "CardPreorderAdventagesChoose")
    internal static let cardPreorderAdventagesControl = ImageAsset(name: "CardPreorderAdventagesControl")
    internal static let cardPreorderAdventagesFun = ImageAsset(name: "CardPreorderAdventagesFun")
    internal static let cardPreorderAdventagesGlobe = ImageAsset(name: "CardPreorderAdventagesGlobe")
    internal static let cardPreorderAdventagesHassle = ImageAsset(name: "CardPreorderAdventagesHassle")
    internal static let cardPreorderAdventagesInstantly = ImageAsset(name: "CardPreorderAdventagesInstantly")
    internal static let cardPreorderBannerKonfety = ImageAsset(name: "CardPreorderBannerKonfety")
    internal static let cardPreorderBannerMan = ImageAsset(name: "CardPreorderBannerMan")
    internal static let cardPreorderCongratBottom = ImageAsset(name: "CardPreorderCongratBottom")
    internal static let cardPreorderCongratCard = ImageAsset(name: "CardPreorderCongratCard")
    internal static let cardPreorderCongratTop = ImageAsset(name: "CardPreorderCongratTop")
    internal static let cardPreorderDetailBackground = ImageAsset(name: "CardPreorderDetailBackground")
    internal static let cardPreorderDetailRectangleBackground = ImageAsset(name: "CardPreorderDetailRectangleBackground")
    internal static let cardPreorderInfoBackground = ImageAsset(name: "CardPreorderInfoBackground")
    internal static let cardPreorderInviteBackground = ImageAsset(name: "CardPreorderInviteBackground")
    internal static let cardPreorderAboutButton = ImageAsset(name: "CardPreorderAboutButton")
    internal static let cardPreorderTariffsButton = ImageAsset(name: "CardPreorderTariffsButton")
    internal static let cameraButton = ImageAsset(name: "cameraButton")
    internal static let completeSuccess = ImageAsset(name: "completeSuccess")
    internal static let completeSuccessIcon = ImageAsset(name: "CompleteSuccessIcon")
    internal static let crossDown = ImageAsset(name: "Cross_down")
    internal static let crypteriumLogo = ImageAsset(name: "CrypteriumLogo")
    internal static let dashbBank = ImageAsset(name: "DashbBank")
    internal static let dashbCRPT = ImageAsset(name: "DashbCRPT")
    internal static let dashbTransfer = ImageAsset(name: "DashbTransfer")
    internal static let dashboardExchange = ImageAsset(name: "DashboardExchange")
    internal static let paymentsTopUp = ImageAsset(name: "PaymentsTopUp")
    internal static let historyOperationReferral = ImageAsset(name: "historyOperationReferral")
    internal static let historyOperationTopupMobile = ImageAsset(name: "historyOperationTopupMobile")
    internal static let emptyHistoryList = ImageAsset(name: "EmptyHistoryList")
    internal static let exchangeTimerIcon = ImageAsset(name: "ExchangeTimerIcon")
    internal static let historyDetailInfoArrow = ImageAsset(name: "HistoryDetailInfoArrow")
    internal static let historyDetailInfoBottom = ImageAsset(name: "HistoryDetailInfoBottom")
    internal static let historyDetailInfoTop = ImageAsset(name: "HistoryDetailInfoTop")
    internal static let historyDetailStatusFailed = ImageAsset(name: "HistoryDetailStatusFailed")
    internal static let historyDetailStatusPending = ImageAsset(name: "HistoryDetailStatusPending")
    internal static let historyOperationStatusFailed = ImageAsset(name: "HistoryOperationStatusFailed")
    internal static let historyOperationStatusPending = ImageAsset(name: "HistoryOperationStatusPending")
    internal static let historyOperationExchange = ImageAsset(name: "historyOperationExchange")
    internal static let historyOperationMobile = ImageAsset(name: "historyOperationMobile")
    internal static let historyOperationReceive = ImageAsset(name: "historyOperationReceive")
    internal static let historyOperationTransfer = ImageAsset(name: "historyOperationTransfer")
    internal static let historyOperationVoucher = ImageAsset(name: "historyOperationVoucher")
    internal static let historyOperationWithdraw = ImageAsset(name: "historyOperationWithdraw")
    internal static let icCrpt = ImageAsset(name: "icCrpt")
    internal static let mlrReward = ImageAsset(name: "mlrReward")
    internal static let ibaNtoMyself = ImageAsset(name: "IBANtoMyself")
    internal static let kycFinalErrorStatusIcon = ImageAsset(name: "KYCFinalErrorStatusIcon")
    internal static let kycFinalProccesStatusIcon = ImageAsset(name: "KYCFinalProccesStatusIcon")
    internal static let kycPhotoInstructionLicence = ImageAsset(name: "KYCPhotoInstructionLicence")
    internal static let kycPhotoInstructionLicenceBackSide = ImageAsset(name: "KYCPhotoInstructionLicenceBackSide")
    internal static let kycPhotoInstructionPassport = ImageAsset(name: "KYCPhotoInstructionPassport")
    internal static let kycPhotoInstructionPassportBackSide = ImageAsset(name: "KYCPhotoInstructionPassportBackSide")
    internal static let kycPhotoInstructionResidential = ImageAsset(name: "KYCPhotoInstructionResidential")
    internal static let kycPhotoInstructionSelfie = ImageAsset(name: "KYCPhotoInstructionSelfie")
    internal static let kycSelectDocumentDriverLicence = ImageAsset(name: "KYCSelectDocumentDriverLicence")
    internal static let kycSelectDocumentIDCard = ImageAsset(name: "KYCSelectDocumentIDCard")
    internal static let kycSelectDocumentPassport = ImageAsset(name: "KYCSelectDocumentPassport")
    internal static let kycSwitchCamera = ImageAsset(name: "KYCSwitchCamera")
    internal static let kycAddImage = ImageAsset(name: "kycAddImage")
    internal static let kycEditImage = ImageAsset(name: "kycEditImage")
    internal static let kycTakeImage = ImageAsset(name: "kycTakeImage")
    internal static let profileContacts = ImageAsset(name: "profileContacts")
    internal static let profileEdit = ImageAsset(name: "profileEdit")
    internal static let profileHostess = ImageAsset(name: "profileHostess")
    internal static let profileIdentity = ImageAsset(name: "profileIdentity")
    internal static let profileResidence = ImageAsset(name: "profileResidence")
    internal static let profileVerified = ImageAsset(name: "profileVerified")
    internal static let thanksForBringing = ImageAsset(name: "thanksForBringing")
    internal static let closeModal = ImageAsset(name: "closeModal")
    internal static let faqIcon = ImageAsset(name: "faqIcon")
    internal static let onboardingIBAN1 = ImageAsset(name: "Onboarding_IBAN_1")
    internal static let onboardingIBAN2 = ImageAsset(name: "Onboarding_IBAN_2")
    internal static let onboardingIBAN3 = ImageAsset(name: "Onboarding_IBAN_3")
    internal static let onboardingIBAN4 = ImageAsset(name: "Onboarding_IBAN_4")
    internal static let onboardingIBANCircle = ImageAsset(name: "Onboarding_IBAN_Circle")
    internal static let sendCrypto1 = ImageAsset(name: "sendCrypto1")
    internal static let sendCrypto2 = ImageAsset(name: "sendCrypto2")
    internal static let sendCrypto3 = ImageAsset(name: "sendCrypto3")
    internal static let sendCrypto4 = ImageAsset(name: "sendCrypto4")
    internal static let welcomeOnboardingBankTransfer = ImageAsset(name: "WelcomeOnboardingBankTransfer")
    internal static let welcomeOnboardingCardPreorder = ImageAsset(name: "WelcomeOnboardingCardPreorder")
    internal static let welcomeOnboardingFuture = ImageAsset(name: "WelcomeOnboardingFuture")
    internal static let welcomeOnboardingNoLimits = ImageAsset(name: "WelcomeOnboardingNoLimits")
    internal static let welcomeOnboardingWallet = ImageAsset(name: "WelcomeOnboardingWallet")
    internal static let onboardingExchangeV21 = ImageAsset(name: "onboardingExchangeV21")
    internal static let onboardingExchangeV22 = ImageAsset(name: "onboardingExchangeV22")
    internal static let onboardingExchangeV23 = ImageAsset(name: "onboardingExchangeV23")
    internal static let topup1 = ImageAsset(name: "topup1")
    internal static let topup2 = ImageAsset(name: "topup2")
    internal static let topup3 = ImageAsset(name: "topup3")
    internal static let arrowDown = ImageAsset(name: "arrowDown")
    internal static let favoriteStar = ImageAsset(name: "favoriteStar")
    internal static let share = ImageAsset(name: "share")
    internal static let share3008 = ImageAsset(name: "share3008")
    internal static let unfavoriteCross = ImageAsset(name: "unfavoriteCross")
    internal static let unfavoriteStar = ImageAsset(name: "unfavoriteStar")
    internal static let infoBtn = ImageAsset(name: "infoBtn")
    internal static let сryptoToFiatGas = ImageAsset(name: "Сrypto-to-fiat-gas")
    internal static let profileFAQDefaultImage = ImageAsset(name: "ProfileFAQDefaultImage")
    internal static let profileMainHeaderLogout = ImageAsset(name: "ProfileMainHeaderLogout")
    internal static let profileMainMenuRowAbout = ImageAsset(name: "ProfileMainMenuRowAbout")
    internal static let profileMainMenuRowDetail = ImageAsset(name: "ProfileMainMenuRowDetail")
    internal static let profileMainMenuRowFAQ = ImageAsset(name: "ProfileMainMenuRowFAQ")
    internal static let profileMainMenuRowSettings = ImageAsset(name: "ProfileMainMenuRowSettings")
    internal static let profileMainMenuSelectList = ImageAsset(name: "ProfileMainMenuSelectList")
    internal static let profileSettingsChangeEmail = ImageAsset(name: "ProfileSettingsChangeEmail")
    internal static let profileSettingsChangePassword = ImageAsset(name: "ProfileSettingsChangePassword")
    internal static let profileSettingsFaceId = ImageAsset(name: "ProfileSettingsFaceId")
    internal static let profileSettingsPrimaryCurrency = ImageAsset(name: "ProfileSettingsPrimaryCurrency")
    internal static let profileSettingsTouchId = ImageAsset(name: "ProfileSettingsTouchId")
    internal static let earn25TopUpMobile = ImageAsset(name: "earn25TopUpMobile")
    internal static let earnTransaction = ImageAsset(name: "earnTransaction")
    internal static let tabbarReferral = ImageAsset(name: "tabbarReferral")
    internal static let tabbarReferralSelected = ImageAsset(name: "tabbarReferralSelected")
    internal static let profileVerificationContactsDone = ImageAsset(name: "ProfileVerificationContactsDone")
    internal static let profileVerificationIdentityAvailable = ImageAsset(name: "ProfileVerificationIdentityAvailable")
    internal static let profileVerificationIdentityDone = ImageAsset(name: "ProfileVerificationIdentityDone")
    internal static let profileVerificationResidenceAvailable = ImageAsset(name: "ProfileVerificationResidenceAvailable")
    internal static let profileVerificationResidenceDisabled = ImageAsset(name: "ProfileVerificationResidenceDisabled")
    internal static let profileVerificationResidenceDone = ImageAsset(name: "ProfileVerificationResidenceDone")
    internal static let loyalty1 = ImageAsset(name: "loyalty1")
    internal static let loyalty2 = ImageAsset(name: "loyalty2")
    internal static let loyalty3 = ImageAsset(name: "loyalty3")
    internal static let loyalty4 = ImageAsset(name: "loyalty4")
    internal static let crptUser = ImageAsset(name: "crptUser")
    internal static let earn25BuyCrypto = ImageAsset(name: "earn25BuyCrypto")
    internal static let earn25CashOut = ImageAsset(name: "earn25CashOut")
    internal static let earn25TopUpCard = ImageAsset(name: "earn25TopUpCard")
    internal static let earnIdentity = ImageAsset(name: "earnIdentity")
    internal static let earnInvite = ImageAsset(name: "earnInvite")
    internal static let earnRegistration = ImageAsset(name: "earnRegistration")
    internal static let earnRewards = ImageAsset(name: "earnRewards")
    internal static let howItWorksBottom = ImageAsset(name: "howItWorksBottom")
    internal static let howItWorksTop = ImageAsset(name: "howItWorksTop")
    internal static let inviteFriends = ImageAsset(name: "inviteFriends")
    internal static let referralClose = ImageAsset(name: "referralClose")
    internal static let referralInviting = ImageAsset(name: "referralInviting")
    internal static let referralProfile = ImageAsset(name: "referralProfile")
    internal static let referralSearch = ImageAsset(name: "referralSearch")
    internal static let referralSignupBonus = ImageAsset(name: "referralSignupBonus")
    internal static let referralWelcome = ImageAsset(name: "referralWelcome")
    internal static let referralWin = ImageAsset(name: "referralWin")
    internal static let tabBarHistory = ImageAsset(name: "tabBarHistory")
    internal static let tabBarMain = ImageAsset(name: "tabBarMain")
    internal static let tabBarProfile = ImageAsset(name: "tabBarProfile")
    internal static let tabBarchatBlack = ImageAsset(name: "tabBarchatBlack")
    internal static let topUpMobileIcon = ImageAsset(name: "TopUpMobileIcon")
    internal static let group5 = ImageAsset(name: "group5")
    internal static let group6 = ImageAsset(name: "group6")
    internal static let arrowUp = ImageAsset(name: "arrowUp")
    internal static let arrowUpW = ImageAsset(name: "arrowUpW")
    internal static let attention = ImageAsset(name: "attention")
    internal static let backButton = ImageAsset(name: "backButton")
    internal static let backButtonTinted = ImageAsset(name: "backButtonTinted")
    internal static let balanceArrowUp = ImageAsset(name: "balance_arrowUp")
    internal static let balanceExchange = ImageAsset(name: "balance_exchange")
    internal static let balancePlus = ImageAsset(name: "balance_plus")
    internal static let balanceTransfer = ImageAsset(name: "balance_transfer")
    internal static let bank = ImageAsset(name: "bank")
    internal static let bankTransfers = ImageAsset(name: "bankTransfers")
    internal static let bankTransfersOnMainScreen = ImageAsset(name: "bankTransfersOnMainScreen")
    internal static let barCodeScanButton = ImageAsset(name: "barCodeScanButton")
    internal static let btsAddressWrong = ImageAsset(name: "btsAddressWrong")
    internal static let burning = ImageAsset(name: "burning")
    internal static let buyCryptoMastercard = ImageAsset(name: "buyCryptoMastercard")
    internal static let buyCryptoVisa = ImageAsset(name: "buyCryptoVisa")
    internal static let cardHistoryIcon = ImageAsset(name: "cardHistoryIcon")
    internal static let chatArrowUp = ImageAsset(name: "chatArrowUp")
    internal static let checkmark = ImageAsset(name: "checkmark")
    internal static let checkmark28 = ImageAsset(name: "checkmark28")
    internal static let clearField = ImageAsset(name: "clearField")
    internal static let closeCross = ImageAsset(name: "closeCross")
    internal static let closeCross28 = ImageAsset(name: "closeCross28")
    internal static let closeCrossBlack = ImageAsset(name: "closeCrossBlack")
    internal static let closeCrossInCircle = ImageAsset(name: "closeCrossInCircle")
    internal static let copy = ImageAsset(name: "copy")
    internal static let crptBurning01Copy = ImageAsset(name: "crptBurning01Copy")
    internal static let ethAttention = ImageAsset(name: "ethAttention")
    internal static let faqArrowDown = ImageAsset(name: "faqArrowDown")
    internal static let faqArrowUp = ImageAsset(name: "faqArrowUp")
    internal static let global = ImageAsset(name: "global")
    internal static let history = ImageAsset(name: "history")
    internal static let ibanFaq = ImageAsset(name: "ibanFaq")
    internal static let info = ImageAsset(name: "info")
    internal static let infoDark = ImageAsset(name: "infoDark")
    internal static let infoWhiteCircle = ImageAsset(name: "infoWhiteCircle")
    internal static let lightning = ImageAsset(name: "lightning")
    internal static let masterCardGrayRound = ImageAsset(name: "masterCardGrayRound")
    internal static let mastercard = ImageAsset(name: "mastercard")
    internal static let mastercardSecureCode = ImageAsset(name: "mastercardSecureCode")
    internal static let menu = ImageAsset(name: "menu")
    internal static let news = ImageAsset(name: "news")
    internal static let onboardingWithdrawal1 = ImageAsset(name: "onboardingWithdrawal1")
    internal static let onboardingWithdrawal2 = ImageAsset(name: "onboardingWithdrawal2")
    internal static let onboardingWithdrawal3 = ImageAsset(name: "onboardingWithdrawal3")
    internal static let onboardingWithdrawal4 = ImageAsset(name: "onboardingWithdrawal4")
    internal static let path1Fill = ImageAsset(name: "path1Fill")
    internal static let payoutArrowUp = ImageAsset(name: "payoutArrowUp")
    internal static let pciDssComplaint = ImageAsset(name: "pciDssComplaint")
    internal static let profile = ImageAsset(name: "profile")
    internal static let quotes = ImageAsset(name: "quotes")
    internal static let receiveAddETHCRPT = ImageAsset(name: "receiveAddETHCRPT")
    internal static let safariIcon = ImageAsset(name: "safariIcon")
    internal static let tabbarCardSelected = ImageAsset(name: "tabbarCardSelected")
    internal static let tabbarCardSelectedNot = ImageAsset(name: "tabbarCardSelectedNot")
    internal static let tabbarDashboardSelected = ImageAsset(name: "tabbarDashboardSelected")
    internal static let tabbarDashboardSelectedNot = ImageAsset(name: "tabbarDashboardSelectedNot")
    internal static let tabbarHistorySelected = ImageAsset(name: "tabbarHistorySelected")
    internal static let tabbarHistorySelectedNot = ImageAsset(name: "tabbarHistorySelectedNot")
    internal static let tabbarProfileSelected = ImageAsset(name: "tabbarProfileSelected")
    internal static let tabbarProfileSelectedNot = ImageAsset(name: "tabbarProfileSelectedNot")
    internal static let telegram = ImageAsset(name: "telegram")
    internal static let verifiedByVisa = ImageAsset(name: "verifiedByVisa")
    internal static let visa = ImageAsset(name: "visa")
    internal static let voucher = ImageAsset(name: "voucher")
    internal static let walletScreenPageEmptyHistoryCell = ImageAsset(name: "walletScreenPageEmptyHistoryCell")
    internal static let walletSelected = ImageAsset(name: "walletSelected")
    internal static let whyCrpt1 = ImageAsset(name: "whyCrpt1")
    internal static let whyCrpt2 = ImageAsset(name: "whyCrpt2")
    internal static let whyCrpt3 = ImageAsset(name: "whyCrpt3")
    internal static let whyCrpt4 = ImageAsset(name: "whyCrpt4")
    internal static let whyCrpt4Esp = ImageAsset(name: "whyCrpt4_esp")
    internal static let whyCrpt4Por = ImageAsset(name: "whyCrpt4_por")
    internal static let whyCrpt4Rus = ImageAsset(name: "whyCrpt4_rus")
    internal static let whyCrpt5 = ImageAsset(name: "whyCrpt5")
  }
}
// swiftlint:enable identifier_name line_length nesting type_body_length type_name

// MARK: - Implementation Details

internal struct ColorAsset {
  internal fileprivate(set) var name: String

  @available(iOS 11.0, tvOS 11.0, watchOS 4.0, OSX 10.13, *)
  internal var color: AssetColorTypeAlias {
    return AssetColorTypeAlias(asset: self)
  }
}

internal extension AssetColorTypeAlias {
  @available(iOS 11.0, tvOS 11.0, watchOS 4.0, OSX 10.13, *)
  convenience init!(asset: ColorAsset) {
    let bundle = Bundle(for: BundleToken.self)
    #if os(iOS) || os(tvOS)
    self.init(named: asset.name, in: bundle, compatibleWith: nil)
    #elseif os(OSX)
    self.init(named: NSColor.Name(asset.name), bundle: bundle)
    #elseif os(watchOS)
    self.init(named: asset.name)
    #endif
  }
}

internal struct DataAsset {
  internal fileprivate(set) var name: String

  #if os(iOS) || os(tvOS) || os(OSX)
  @available(iOS 9.0, tvOS 9.0, OSX 10.11, *)
  internal var data: NSDataAsset {
    return NSDataAsset(asset: self)
  }
  #endif
}

#if os(iOS) || os(tvOS) || os(OSX)
@available(iOS 9.0, tvOS 9.0, OSX 10.11, *)
internal extension NSDataAsset {
  convenience init!(asset: DataAsset) {
    let bundle = Bundle(for: BundleToken.self)
    #if os(iOS) || os(tvOS)
    self.init(name: asset.name, bundle: bundle)
    #elseif os(OSX)
    self.init(name: NSDataAsset.Name(asset.name), bundle: bundle)
    #endif
  }
}
#endif

internal struct ImageAsset {
  internal fileprivate(set) var name: String

  internal var image: AssetImageTypeAlias {
    let bundle = Bundle(for: BundleToken.self)
    #if os(iOS) || os(tvOS)
    let image = AssetImageTypeAlias(named: name, in: bundle, compatibleWith: nil)
    #elseif os(OSX)
    let image = bundle.image(forResource: NSImage.Name(name))
    #elseif os(watchOS)
    let image = AssetImageTypeAlias(named: name)
    #endif
    guard let result = image else { fatalError("Unable to load image named \(name).") }
    return result
  }
}

internal extension AssetImageTypeAlias {
  @available(iOS 1.0, tvOS 1.0, watchOS 1.0, *)
  @available(OSX, deprecated,
    message: "This initializer is unsafe on macOS, please use the ImageAsset.image property")
  convenience init!(asset: ImageAsset) {
    #if os(iOS) || os(tvOS)
    let bundle = Bundle(for: BundleToken.self)
    self.init(named: asset.name, in: bundle, compatibleWith: nil)
    #elseif os(OSX)
    self.init(named: NSImage.Name(asset.name))
    #elseif os(watchOS)
    self.init(named: asset.name)
    #endif
  }
}

private final class BundleToken {}
